CREATE PROCEDURE loadBankOZKLookup()
LANGUAGE SQL
AS $$
COPY bankOZKLookup(LOOKUP,LOOKUPEXTENDED,TRANSACTIONTYPE,ORIGINALDESCRIPTION,TRANSACTIONTYPEDETAIL) FROM '/home/ec2-user/sql/bankOZKLookup.csv' DELIMITER ',' CSV HEADER;
$$;
